#!/bin/bash

#=======================================================#
#   Bergische Universität Wuppertal                     #
#                                                       #
#   Author:                                             #
#      Sebastian Sennewald                              #
#                                                       #
#   Source:                                             #
#      https://github.com/buwzim/moodle-update-script   #
#                                                       #
#   License:                                            #
#      GPLv3, see LICENSE file                          #
#                                                       #
#=======================================================#

# functions
function checkstatus() {

        # set to default
        CONTINUE="null"

        if test $? -ne 0
        then
                # ask user to continue
                until test "$CONTINUE" = "y" -o "$CONTINUE" = "n"
                do
                        printf "%s" "FAILED > Continue? (y/n)" 1>&2
                        read -r CONTINUE
                done

                        if test "$CONTINUE" = "n"
                        then
                                printf "%s \n" " "
                                printf "%s \n" "process cancelled"
                                printf "%s \n" " "
                                exit 66
                        fi

        else
                printf "%s \n" "OK"
        fi

        # set to default
        CONTINUE="null"
}

# start
tput clear

printf "%s \n" " "
printf "%s \n" " "
printf "%s \n" "+------------------------------+"
printf "%s \n" "+     moodle update script     +"
printf "%s \n" "+------------------------------+"


# check if version parameter is given
if test -z $1
then
        printf "%s" "enter target version (\"x.y\"): "
        read -r MOODLE_VERSION_NEXT
else
        MOODLE_VERSION_NEXT=$1
fi


# list of plugin directories
FOLDER[0]="theme"
FOLDER[1]="mod"
FOLDER[2]="report"
FOLDER[3]="auth"
FOLDER[4]="filter"
FOLDER[5]="local"
FOLDER[6]="repository"
FOLDER[7]="question/format"
FOLDER[8]="portfolio"
FOLDER[9]="lib/editor/atto/plugins"
FOLDER[10]="anmeldung"
FOLDER[11]="blocks"
FOLDER[12]="mod/assign/submission"
FOLDER[13]="question/type"
FOLDER[14]="grade/report"
FOLDER[15]="course/format"
FOLDER[16]="availability"
FOLDER[17]="question/behaviour"

# settings
CONTINUE="null"
WEBUSER="www-data"
WEB_PATH="/var/www"
PHP_PATH="/usr/bin/php"
CURL_PATH="/usr/bin/curl"
MOODLE_LINK_NAME="moodle"
MOODLE_PATH="$WEB_PATH/$MOODLE_LINK_NAME"
MOODLE_CONFIG="$MOODLE_PATH/config.php"


# check moodle config file
printf "%-25s %s" "moodle config" ": "

        if test ! -e $MOODLE_CONFIG
        then
                printf "%s \n" "FAILED" 1>&2
                exit 1
        else
                printf "%s \n" "OK"


                echo "$1" | grep "^moodle_[0-9]*\.[0-9]*_" > /dev/null
        fi


# get moodle data path
TEMP1=$(grep "^\$CFG->dataroot" $MOODLE_PATH/config.php | cut -d" " -f4)
TEMP2=${TEMP1//\'}
MOODLE_DATA_PATH=${TEMP2//\;}

# check moodle data path
printf "%-25s %s" "moodle data folder" ": "

        if test ! -d $MOODLE_DATA_PATH
        then
                printf "%s \n" "FAILED" 1>&2
                exit 1
        else
                printf "%s \n" "OK"
        fi


# language files
LANG_LICENSE_EN="$MOODLE_PATH/lang/en/license.php"
LANG_LICENSE_DE="$MOODLE_DATA_PATH/lang/de/license.php"

# build url version parameter
MOODLE_VERSION_NEXT_URL=${MOODLE_VERSION_NEXT//.}

# get current moodle version
if test -h $MOODLE_PATH
then
        LINK_CURRENT_TARGET=$(readlink "$MOODLE_PATH")
        MOODLE_PATH_REAL="$LINK_CURRENT_TARGET"
        MOODLE_VERSION_NOW=${LINK_CURRENT_TARGET//$WEB_PATH\/moodle_}
fi

# check if url parameter is given
if test $2
then
        MOODLE_DOWNLOAD_URL=$2
        MOODLE_DOWNLOAD_FILE=${MOODLE_DOWNLOAD_URL##*/}
else
        MOODLE_DOWNLOAD_FILE="moodle-latest-${MOODLE_VERSION_NEXT_URL}.zip"
        MOODLE_DOWNLOAD_URL="https://download.moodle.org/download.php/direct/stable${MOODLE_VERSION_NEXT_URL}/$MOODLE_DOWNLOAD_FILE"
fi


MOODLE_TEMP="moodle_temp"
MOODLE_TEMP_PATH="$WEB_PATH/$MOODLE_TEMP"

MOODLE_NEXT="moodle_$MOODLE_VERSION_NEXT"
MOODLE_NEXT_PATH="$WEB_PATH/$MOODLE_NEXT"

BACKUP_DATE=$(date '+%F_%H-%M-%S')
BACKUP_NAME="moodle_${MOODLE_VERSION_NOW}_$BACKUP_DATE"
BACKUP_PATH="$WEB_PATH/$BACKUP_NAME"



# ask if versions are corret
printf "%s \n" " "
printf "%-25s %s \n" "target version" ": $MOODLE_VERSION_NEXT"
printf "%-25s %s \n" "current version" ": $MOODLE_VERSION_NOW"
printf "%s \n" " "


# show download url
printf "%-25s %s %s \n" "download url" ":" "$MOODLE_DOWNLOAD_URL"


# download latest moodle
printf "%-25s %s" "download moodle" ": "

        wget -q $MOODLE_DOWNLOAD_URL
        checkstatus


# file size
printf "%-25s %s" "file size (MB)" ": "

        FILESIZE=$(cat $MOODLE_DOWNLOAD_FILE | wc -c)
        FILESIZE=$(( FILESIZE / 1024 / 1024 ))

        printf "%d" "$FILESIZE"

        if test $FILESIZE -eq 0
        then
                printf "%s \n" " FAILED" 1>&2
                exit 65
        else
                printf "\n"
        fi


# check web path: folder
printf "%-25s %s" "web path (folder)" ": "

        if test ! -d $WEB_PATH
        then
                printf "%s \n" "FAILED" 1>&2
                exit 1
        else
                printf "%s \n" "OK"
        fi


# check web path: access
printf "%-25s %s" "web path (access)" ": "

        if test ! -e $WEB_PATH
        then
                printf "%s \n" "FAILED" 1>&2
                exit 2
        else
                printf "%s \n" "OK"
        fi


# check php
printf "%-25s %s" "php" ": "

        if test ! -e $PHP_PATH
        then
                printf "%s \n" "FAILED"  1>&2
                exit 3
        else
                printf "%s \n" "OK"
        fi


# check if cURL is available
printf "%-25s %s" "cURL" ": "

        if test ! -e $CURL_PATH
        then
                printf "%s \n" "FAILED" 1>&2
                exit 5
        else
                printf "%s \n" "OK"
        fi


# check if a new version is available
printf "%-25s %s" "script version" ": "

        # download version file
        curl -s https://raw.githubusercontent.com/buwzim/moodle-update-script/master/version --output remoteversion

        # save version numbers into var
        SCRIPT_VERSION_REMOTE=$(cat remoteversion)
        SCRIPT_VERSION_LOCAL=$(cat version)

        if test $SCRIPT_VERSION_LOCAL -eq $SCRIPT_VERSION_REMOTE
        then
                printf "%s \n" "OK"
        else
                printf "%s %s %d %s %d %s \n" "WARNING" "(local: " $SCRIPT_VERSION_LOCAL " | remote: " $SCRIPT_VERSION_REMOTE ")" 1>&2
        fi

        rm remoteversion


# check current moodle path
printf "%-25s %s" "moodle path" ": "

        if test ! -d $MOODLE_PATH_REAL
        then
                printf "%s \n" "FAILED" 1>&2
                exit 4
        else
                printf "%s \n" "OK"
        fi


# go to web folder
printf "%-25s %s" "go to web folder" ": "

        cd $WEB_PATH
        checkstatus


# all pre-checks done
printf "%s \n" " "
printf "%s \n" "all pre-checks successfull"

        # ask user to continue
        until test "$CONTINUE" = "y" -o "$CONTINUE" = "n"
        do
                printf "%s" "continue? (y/n): "
                read -n 1 CONTINUE
        done

                if test "$CONTINUE" = "n"
                then
                        printf "%s \n" " "
                        printf "%s \n" "goodbye."
                        printf "%s \n" " "
                        exit 1
                fi

# user wants to continue
printf "%s \n" " "


# moodle -> maintenance mode -> enable
printf "%-25s %s" "enable maintenance" ": "

        $PHP_PATH $MOODLE_PATH_REAL/admin/cli/maintenance.php --enableold > /dev/null
        checkstatus


# time to wait in maintenance mode until work continues
printf "%-25s %s" "minutes to wait" ": "

        read -r WAIT_FOR_MAINTENANCE

                until test $WAIT_FOR_MAINTENANCE -ge 0
                do
                        printf "%s \n" " "
                        printf "%-25s %s" "minutes to wait" ": "

                        read -r WAIT_FOR_MAINTENANCE
                done

        sleep ${WAIT_FOR_MAINTENANCE}m
        printf "%-25s %s \n" "waited $WAIT_FOR_MAINTENANCE minutes" ": OK"


# stay in maintenance mode?
until test "$STAY_IN_MAINTENANCE" = "y" -o "$STAY_IN_MAINTENANCE" = "n"
do
        printf "%-25s %s" "stay in maintenance (y/n)" ": "
        read -n 1 STAY_IN_MAINTENANCE
done

printf "\n"


# create backup
printf "%-25s %s" "moodle backup" ": "

        cp -r $MOODLE_PATH_REAL/ $BACKUP_PATH/
        checkstatus


# delete old moodle folder
printf "%-25s %s" "delete old moodle" ": "

        rm -r "$MOODLE_PATH_REAL"
        checkstatus


# unzip
printf "%-25s %s" "unzip to temp folder" ": "

        unzip -q $WEB_PATH/$MOODLE_DOWNLOAD_FILE -d $MOODLE_TEMP_PATH
        checkstatus


printf "%-25s %s" "move to version folder" ": "

        mv $MOODLE_TEMP_PATH/moodle/ $MOODLE_NEXT_PATH/
        checkstatus


# clean up
printf "%-25s %s" "delete temp folder" ": "

        rm -r $MOODLE_TEMP_PATH/
        checkstatus


printf "%-25s %s" "delete downloaded file" ": "

        rm $MOODLE_DOWNLOAD_FILE
        checkstatus


# copy config
printf "%-25s %s" "copy: config.php" ": "

        if test -e $BACKUP_PATH/config.php
        then
                cp $BACKUP_PATH/config.php $MOODLE_NEXT_PATH/config.php
                checkstatus
        else
                printf "%s \n" "file missing" 1>&2
                exit 11
        fi


# copy plugins
printf "%s \n" " "

        # choose copy mode
        until test "$COPYALL" = "y" -o "$COPYALL" = "n"
        do
                printf "%s" "copy ALL plugins? (y/n): "
                read -n 1 COPYALL
        done


printf "%s \n" " "
printf "%s \n" "begin to copy plugins ..."

# make a list of all plugin categories
for PLUGINDIR in ${FOLDER[@]}
do
        # make a list of all sub-folders of current plugin category
        for PLUGIN in $(ls $BACKUP_PATH/$PLUGINDIR/)
        do
                # check if current list item is MISSING inside the new mooddle folder
                if test ! -d $MOODLE_NEXT_PATH/$PLUGINDIR/$PLUGIN
                then
                        # if current list item is a folder
                        if test -d $BACKUP_PATH/$PLUGINDIR/$PLUGIN
                        then

                                # pre-define user input if copy mode is set to ALL
                                if test "$COPYALL" = "y"
                                then
                                        CONTINUE="y"
                                fi

                                # copy folder if wanted
                                until test "$CONTINUE" = "y" -o "$CONTINUE" = "n"
                                do
                                        printf "%-46s %s" "Copy $PLUGINDIR/$PLUGIN? (y/n)" ": "
                                        read -n 1 -s CONTINUE
                                done

                                # copy yes
                                if test "$CONTINUE" = "y"
                                then
                                        # create parent folder if missing
                                        if test ! -d $MOODLE_NEXT_PATH/$PLUGINDIR
                                        then
                                                mkdir $MOODLE_NEXT_PATH/$PLUGINDIR
                                        fi

                                        cp -r $BACKUP_PATH/$PLUGINDIR/$PLUGIN/ $MOODLE_NEXT_PATH/$PLUGINDIR/$PLUGIN/
                                        checkstatus
                                else
                                        printf "%s \n" "SKIPPED"
                                fi

                                # set to default
                                CONTINUE="null"
                        fi
                fi
        done
done


# update sym link
printf "%s \n" " "
printf "%-46s %s" "update symlink" ": "

        rm $MOODLE_PATH && ln -s $MOODLE_NEXT_PATH $MOODLE_PATH
        checkstatus


# update moodle
printf "%-25s \n" "update moodle ..."

        $PHP_PATH $MOODLE_PATH/admin/cli/upgrade.php --non-interactive

        if test $? -ne 0
        then
                printf "%s \n" " "
                printf "%-25s %s \n" "upgrade moodle" ": failed" 1>&2
                exit 12
        else
                printf "%s \n" " "
                printf "%-25s %s \n" "upgrade moodle" ": OK"
        fi


# modify license lang strings
printf "%-25s %s" "language strings (en)" ": "

        grep 'ungeprueft' $LANG_LICENSE_EN > /dev/null

        if test $? -eq 1
        then
                echo "\$string['freielizenz'] = 'Freie Lizenz';" >> $LANG_LICENSE_EN
                echo "\$string['52a'] = 'VG Wort';" >> $LANG_LICENSE_EN
                echo "\$string['gemeinfrei'] = 'Gemeinfrei';" >> $LANG_LICENSE_EN
                echo "\$string['ungeprueft'] = 'Ungeprüft';" >> $LANG_LICENSE_EN

                printf "%s \n" "OK"
        else
                printf "%s \n" "OK"
        fi


printf "%-25s %s" "language strings (de)" ": "

        grep 'ungeprueft' $LANG_LICENSE_DE > /dev/null

        if test $? -eq 1
        then
                echo "\$string['freielizenz'] = 'Freie Lizenz';" >> $LANG_LICENSE_DE
                echo "\$string['52a'] = 'VG Wort';" >> $LANG_LICENSE_DE
                echo "\$string['gemeinfrei'] = 'Gemeinfrei';" >> $LANG_LICENSE_DE
                echo "\$string['ungeprueft'] = 'Ungeprüft';" >> $LANG_LICENSE_DE

                printf "%s \n" "OK"
        else
                printf "%s \n" "OK"
        fi


# set rights
printf "%-25s %s" "update permissions" ": "

        chown -R "$WEBUSER:$WEBUSER" $MOODLE_NEXT_PATH && chown -R "$WEBUSER:$WEBUSER" $MOODLE_PATH
        checkstatus


# moodle -> maintenance mode -> disable
if test "$STAY_IN_MAINTENANCE" = "n"
then
        printf "%-25s %s" "disable maintenance" ": "

        $PHP_PATH $MOODLE_PATH/admin/cli/maintenance.php --disable > /dev/null
        checkstatus
else
        printf "%-25s %s \n" "stay in maintenance" ": OK"
fi


# delete cache
printf "%-25s %s" "purge cache" ": "

        $PHP_PATH $MOODLE_PATH/admin/cli/purge_caches.php
        checkstatus


printf "%s \n" " "
printf "%s \n" " "
printf "%s \n" "All jobs done."
printf "%s \n" " "
